input  {
  beats  {
    port => 5044
  }
  http  {
    port => 8080
    codec => json
  }
}


filter  {
  if [source_type] == "security_scan"  {
    mutate  {
      add_field =>  {
        "[@metadata][target_index]" => "security-scan-%{+YYYY.MM.dd}"
        }
      }
    }
  else {
    mutate {
      add_field => {
        "[@metadata][target_index]" => "application-logs-%{+YYYY.MM.dd}"
        }
      }
    }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    index => "%{[@metadata][target_index]}"
    }
  stdout {
    codec => rubydebug
    }
}
