name: Bandit Security Scan



on:

  push:

    branches:

      - master



  pull_request:

    branches:

      - master



jobs:

  bandit:

    runs-on: ubuntu-latest



    steps:

      - name: Checkout repository

        uses: actions/checkout@v4



      - name: Pull Bandit Docker image

        run: docker pull cytopia/bandit:latest-py3.8


      - name: Run Bandit

        run: |

          docker run --rm \

            -v "${{ github.workspace }}:/src" \

            -w /src \

            cytopia/bandit:latest-py3.8 \

            -r .
            --severity-level high
