name: DAST

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:

  check-staging:

    runs-on: ubuntu-latest

    environment:

      name: staging

    steps:

      - name: Check staging is reachable

        run: curl -fsS "$STAGING_URL"

        env:

          STAGING_URL: ${{ vars.STAGING_URL }}

  zap-full-scan:

    runs-on: ubuntu-latest

    needs: check-staging

    environment:

      name: staging

    steps:

      - name: Pull OWASP ZAP image

        run: docker pull zaproxy/zap-stable

      - name: Run OWASP ZAP full  scan

        run: |

          docker run --rm \
          --user 0 \
          -v "${{ github.workspace }}:/zap/wrk/:rw" \
          zaproxy/zap-stable \
          zap-full-scan.py \
          -t "$STAGING_URL" \
          -r zap-report.html \
          -j zap-report.json

        env:

          STAGING_URL: ${{ vars.STAGING_URL }}


      - name: Upload baseline report

        if: always()

        uses: actions/upload-artifact@v4

        with:
          name: zap-full-scan-report

          path: |
            zap-report.html \
            zap-report.json
