name: Owasp dependency check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
 dependency-check:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull dependency check image
        run: docker pull owasp/dependency-check

      - name: Create reports folder
        run: mkdir -p reports

      - name: remove old corrupt database
        run: rm -rf dependency-check-data

      - name: Owasp Dependency check
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/src" \
          owasp/dependency-check:latest \
          --scan /src \
          --format HTML \
          --out /src/reports \
          --nvdApiKey "${{ secrets.NVD_API_KEY }}" \
          --failOnCVSS 7
      - name: Find reports folder
        if: always()
        run: |
           find . -name
           "dependency-check-report*"
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: dependency-check-report
         path: reports/
